//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryWCF.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class EMP
    {
        [DataMember]
        public int EMPNO { get; set; }
        [DataMember]
        public string ENAME { get; set; }
        [DataMember]
        public string JOB { get; set; }
        //[DataMember]
        //public int MGR { get; set; }
        //[DataMember]
        //public DateTime HIREDATE { get; set; }
        [DataMember]
        public int SAL { get; set; }
        //[DataMember]
        //public int COMM { get; set; }
        //[DataMember]
        public int DEPTNO { get; set; }
       // [DataMember]
        //public string EMAIL { get; set; }
    }
}
